-- Create a table to store role cooldowns
CREATE TABLE IF NOT EXISTS role_cooldowns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    role_id TEXT NOT NULL,
    role_name TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Constraint to prevent duplicate active cooldowns for same role/user
    CONSTRAINT unique_active_role_cooldown UNIQUE (user_id, role_id)
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_role_cooldowns_user_expires ON role_cooldowns(user_id, expires_at);
