CREATE TABLE IF NOT EXISTS public.money_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    amount NUMERIC DEFAULT 0,
    transaction_type TEXT NOT NULL, -- 'salary_collection', 'wire_transfer', 'store_purchase', etc.
    description TEXT,
    balance_after NUMERIC DEFAULT 0,
    currency TEXT DEFAULT 'cash', -- 'cash' or 'bank'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster queries by user
CREATE INDEX IF NOT EXISTS idx_money_history_user_id ON public.money_history(user_id);
