-- Create erlc_pending_actions table
create table if not exists public.erlc_pending_actions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    command text not null,
    reason text,
    roblox_username text,
    roblox_id text,
    status text default 'pending' check (status in ('pending', 'completed', 'failed')),
    attempts integer default 0,
    last_attempt timestamp with time zone,
    error_log text
);

-- Add index for status for faster polling
create index if not exists idx_erlc_pending_actions_status on public.erlc_pending_actions (status);

-- Enable RLS (Optional, but good practice)
alter table public.erlc_pending_actions enable row level security;

-- Allow read/write access (Adjust policies as needed)
create policy "Enable read access for all users" on public.erlc_pending_actions for select using (true);
create policy "Enable insert for authenticated users only" on public.erlc_pending_actions for insert with check (auth.role() = 'authenticated');
create policy "Enable update for service role only" on public.erlc_pending_actions for update using (true);
