-- VEHICLES SYSTEM
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    plate TEXT NOT NULL,
    model TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Particular', 'SUV', 'Oficial', 'Pesado')),
    color TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT unique_plate_per_guild UNIQUE (guild_id, plate)
);

-- TEMP ROLES SYSTEM
CREATE TABLE IF NOT EXISTS temp_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role_id TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    assigned_by TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- MOD REQUESTS LOG (Optional, good for history)
CREATE TABLE IF NOT EXISTS mod_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    reason TEXT NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, resolved
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
