-- Create AI Memory table
create table if not exists public.ai_memory (
  id bigint generated by default as identity primary key,
  memory_type text not null check (memory_type in ('TICKET_RESOLUTION', 'USER_INTERACTION', 'GENERAL_KNOWLEDGE', 'ERROR_LOG')),
  source_id text, -- Channel ID, Ticket ID, Message ID, or 'MANUAL'
  user_id text, -- ID of the user involved (optional)
  summary text not null, -- The distilled knowledge/lesson
  raw_content text, -- Full context/transcript if needed
  tags text[], -- Array of strings for better retrieval (e.g. ['bug', 'economy', 'urgent'])
  confidence_score float default 1.0, -- How confident the AI is in this memory (0.0 to 1.0)
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.ai_memory enable row level security;

-- Policy: Allow read access to all (or restrict to service role if strictly internal)
-- For now, allowing service role full access and authenticated users read access might be safe, 
-- but usually bot uses service role so RLS isn't strictly blocking it.
create policy "Allow full access to service role"
on public.ai_memory
for all
to service_role
using (true)
with check (true);

-- Index for searching tags
create index if not exists ai_memory_tags_idx on public.ai_memory using gin (tags);
