-- Tabla para controlar las placas (badges) de staff
CREATE TABLE IF NOT EXISTS staff_badges (
    discord_id TEXT PRIMARY KEY,
    badge_type TEXT NOT NULL, -- 'ST', 'AD', 'JD'
    badge_number INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla para encolar comandos de ERLC si el usuario está offline
CREATE TABLE IF NOT EXISTS pending_erlc_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id TEXT NOT NULL,
    roblox_username TEXT NOT NULL,
    command TEXT NOT NULL,
    status TEXT DEFAULT 'pending', -- 'pending', 'completed', 'failed'
    attempts INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indices para búsqueda rápida
CREATE INDEX IF NOT EXISTS idx_staff_badges_type ON staff_badges(badge_type);
CREATE INDEX IF NOT EXISTS idx_pending_erlc_status ON pending_erlc_commands(status);
