-- Create server_settings table
CREATE TABLE IF NOT EXISTS server_settings (
    guild_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (guild_id, key)
);

-- Create treasury_logs table
CREATE TABLE IF NOT EXISTS treasury_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    type TEXT NOT NULL, -- DEPOSIT, WITHDRAW
    source TEXT NOT NULL, -- Taxes, Licenses, etc
    reason TEXT,
    balance_after NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Initial Balance for Main Guild (Optional, defaults to 0 by code)
INSERT INTO server_settings (guild_id, key, value, description)
VALUES ('1263321528657805364', 'govt_treasury_balance', '0', 'Fondos del Gobierno (Tesorería)')
ON CONFLICT (guild_id, key) DO NOTHING;
