const fs = require('fs');
const path = require('path');

console.log('🔄 Convirtiendo Schema PostgreSQL → Oracle...\n');

// Mapeo de tipos PostgreSQL a Oracle
const typeMapping = {
    'SERIAL': 'NUMBER GENERATED BY DEFAULT AS IDENTITY',
    'BIGSERIAL': 'NUMBER(19) GENERATED BY DEFAULT AS IDENTITY',
    'INTEGER': 'NUMBER(10)',
    'BIGINT': 'NUMBER(19)',
    'SMALLINT': 'NUMBER(5)',
    'TEXT': 'CLOB',
    'VARCHAR': 'VARCHAR2',
    'CHAR': 'CHAR',
    'BOOLEAN': 'NUMBER(1)',
    'TIMESTAMP': 'TIMESTAMP',
    'TIMESTAMP WITH TIME ZONE': 'TIMESTAMP WITH TIME ZONE',
    'TIMESTAMPTZ': 'TIMESTAMP WITH TIME ZONE',
    'DATE': 'DATE',
    'NUMERIC': 'NUMBER',
    'DECIMAL': 'NUMBER',
    'REAL': 'BINARY_FLOAT',
    'DOUBLE PRECISION': 'BINARY_DOUBLE',
    'JSONB': 'CLOB',
    'JSON': 'CLOB',
    'UUID': 'VARCHAR2(36)',
    'BYTEA': 'BLOB'
};

// Schema manual basado en tu estructura actual
const oracleSchema = `-- Oracle Cloud Schema
-- Generated for: nacionmx-bot
-- Target: Autonomous Database (Always Free)
-- Generated: ${new Date().toISOString()}

-- =====================================================
-- TABLA: citizens
-- =====================================================
CREATE TABLE citizens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id VARCHAR2(100) UNIQUE NOT NULL,
    full_name VARCHAR2(200) NOT NULL,
    birth_date VARCHAR2(20),
    gender VARCHAR2(20),
    nationality VARCHAR2(100) DEFAULT 'Mexicana',
    curp VARCHAR2(18) UNIQUE,
    photo_url CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_citizens_discord ON citizens(discord_id);
CREATE INDEX idx_citizens_curp ON citizens(curp);

-- =====================================================
-- TABLA: debit_cards
-- =====================================================
CREATE TABLE debit_cards (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number VARCHAR2(16) UNIQUE NOT NULL,
    discord_user_id VARCHAR2(100) NOT NULL,
    citizen_id NUMBER,
    balance NUMBER(15,2) DEFAULT 0,
    card_type VARCHAR2(100) DEFAULT 'NMX Débito',
    status VARCHAR2(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_debit_citizen FOREIGN KEY (citizen_id) REFERENCES citizens(id)
);

CREATE INDEX idx_debit_discord ON debit_cards(discord_user_id);
CREATE INDEX idx_debit_status ON debit_cards(status);

-- =====================================================
-- TABLA: credit_cards
-- =====================================================
CREATE TABLE credit_cards (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number VARCHAR2(16) UNIQUE NOT NULL,
    citizen_id NUMBER NOT NULL,
    card_type VARCHAR2(100) NOT NULL,
    credit_limit NUMBER(15,2) DEFAULT 0,
    current_balance NUMBER(15,2) DEFAULT 0,
    interest_rate NUMBER(5,2) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_credit_citizen FOREIGN KEY (citizen_id) REFERENCES citizens(id)
);

CREATE INDEX idx_credit_citizen ON credit_cards(citizen_id);
CREATE INDEX idx_credit_status ON credit_cards(status);

-- =====================================================
-- TABLA: debit_transactions
-- =====================================================
CREATE TABLE debit_transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_user_id VARCHAR2(100) NOT NULL,
    transaction_type VARCHAR2(50) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    description VARCHAR2(500),
    balance_after NUMBER(15,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_transactions_user ON debit_transactions(discord_user_id);
CREATE INDEX idx_transactions_type ON debit_transactions(transaction_type);
CREATE INDEX idx_transactions_date ON debit_transactions(created_at);

-- =====================================================
-- TABLA: companies
-- =====================================================
CREATE TABLE companies (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) UNIQUE NOT NULL,
    owner_ids CLOB, -- JSON array
    industry VARCHAR2(100),
    capital NUMBER(15,2) DEFAULT 0,
    is_private NUMBER(1) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_companies_status ON companies(status);

-- =====================================================
-- TABLA: user_purchases
-- =====================================================
CREATE TABLE user_purchases (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(100) NOT NULL,
    item_id VARCHAR2(100) NOT NULL,
    purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'active'
);

CREATE INDEX idx_purchases_user ON user_purchases(user_id);
CREATE INDEX idx_purchases_item ON user_purchases(item_id);
CREATE INDEX idx_purchases_status ON user_purchases(status);

-- =====================================================
-- TABLA: casino_chips
-- =====================================================
CREATE TABLE casino_chips (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(100) UNIQUE NOT NULL,
    chips NUMBER(15,2) DEFAULT 0,
    total_won NUMBER(15,2) DEFAULT 0,
    total_lost NUMBER(15,2) DEFAULT 0,
    games_played NUMBER(10) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chips_user ON casino_chips(user_id);

-- =====================================================
-- TABLA: tax_evasion_history
-- =====================================================
CREATE TABLE tax_evasion_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id VARCHAR2(100) NOT NULL,
    user_id VARCHAR2(100) NOT NULL,
    evasion_type VARCHAR2(50) NOT NULL,
    tax_amount NUMBER(15,2),
    fine_amount NUMBER(15,2),
    suspicion_level NUMBER(3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tax_user ON tax_evasion_history(user_id);
CREATE INDEX idx_tax_type ON tax_evasion_history(evasion_type);

-- =====================================================
-- TABLA: pending_transfers
-- =====================================================
CREATE TABLE pending_transfers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id VARCHAR2(100) NOT NULL,
    receiver_id VARCHAR2(100) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    reason VARCHAR2(500),
    release_date TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_transfers_status ON pending_transfers(status);
CREATE INDEX idx_transfers_release ON pending_transfers(release_date);

-- =====================================================
-- TABLA: giro_transfers
-- =====================================================
CREATE TABLE giro_transfers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id VARCHAR2(100) NOT NULL,
    receiver_id VARCHAR2(100) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    reason VARCHAR2(500),
    release_date TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_giro_status ON giro_transfers(status);
CREATE INDEX idx_giro_release ON giro_transfers(release_date);

-- =====================================================
-- TABLA: privacy_accounts
-- =====================================================
CREATE TABLE privacy_accounts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(100) NOT NULL,
    level VARCHAR2(50) NOT NULL,
    offshore_name VARCHAR2(200),
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_privacy_user ON privacy_accounts(user_id);
CREATE INDEX idx_privacy_expires ON privacy_accounts(expires_at);

-- =====================================================
-- TABLA: bot_heartbeats
-- =====================================================
CREATE TABLE bot_heartbeats (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id VARCHAR2(100) UNIQUE NOT NULL,
    last_heartbeat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(50) DEFAULT 'active'
);

CREATE INDEX idx_heartbeat_instance ON bot_heartbeats(instance_id);

-- =====================================================
-- Comentarios finales
-- =====================================================
COMMENT ON TABLE citizens IS 'Ciudadanos registrados en el sistema';
COMMENT ON TABLE debit_cards IS 'Tarjetas de débito NMX';
COMMENT ON TABLE credit_cards IS 'Tarjetas de crédito NMX';
COMMENT ON TABLE companies IS 'Empresas registradas';
COMMENT ON TABLE casino_chips IS 'Fichas de casino por usuario';

-- =====================================================
-- FIN DEL SCHEMA
-- =====================================================
`;

// Guardar schema Oracle
const exportsDir = path.join(__dirname, '../exports');
if (!fs.existsSync(exportsDir)) {
    fs.mkdirSync(exportsDir, { recursive: true });
}

const oraclePath = path.join(exportsDir, 'oracle_schema.sql');
fs.writeFileSync(oraclePath, oracleSchema);

console.log('✅ Schema Oracle generado exitosamente!');
console.log(`📁 Ubicación: ${oraclePath}\n`);
console.log('📋 Tablas incluidas:');
console.log('   - citizens');
console.log('   - debit_cards');
console.log('   - credit_cards');
console.log('   - debit_transactions');
console.log('   - companies');
console.log('   - user_purchases');
console.log('   - casino_chips');
console.log('   - tax_evasion_history');
console.log('   - pending_transfers');
console.log('   - giro_transfers');
console.log('   - privacy_accounts');
console.log('   - bot_heartbeats');
console.log('\n💡 Próximo paso: Ejecutar este schema en Oracle Cloud');
console.log('   sqlplus ADMIN/<password>@nacionmxdb_high @exports/oracle_schema.sql\n');
